//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SerialCtrlDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERIALCTRLDEMO_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PWENTRY              129
#define IDD_DIALOG_ADMIN1               130
#define IDD_DIALOG_ADMIN2               131
#define IDR_MENU1                       132
#define IDC_COMBO_SN                    1000
#define IDC_COMBO_BR                    1001
#define IDC_BUTTON_OPEN                 1002
#define IDC_LIST_READ                   1004
#define IDC_EDIT_WRITE                  1005
#define IDC_BUTTON_WR                   1006
#define IDC_STATIC_INFO                 1007
#define IDC_STATIC_SN                   1013
#define IDC_EDIT_BARCODE                1014
#define IDC_BUTTON_ENTER                1016
#define IDC_BUTTON_FAIL                 1017
#define IDC_BUTTON_PASS2                1018
#define IDC_BUTTON_PASS                 1018
#define IDC_BUTTON_PREVIOUS             1019
#define IDC_BUTTON_HALT                 1020
#define IDC_STATIC_SN2                  1021
#define IDC_STATIC_PARTNO               1021
#define IDC_STATIC_MODELGROUP           1022
#define IDC_EDIT2                       1025
#define IDC_EDIT_PARTNUMBER             1025
#define IDC_EDIT_NUM_SCANS              1025
#define IDC_EDIT_OUTPUT_FILENAME        1025
#define IDC_EDIT_OUTFILE                1025
#define IDC_EDIT_NUM_AVERAGES           1026
#define IDC_EDIT_TEST1                  1031
#define IDC_EDIT_TEST2                  1032
#define IDC_EDIT_TEST3                  1033
#define IDC_EDIT_TEST4                  1034
#define IDC_EDIT_TEST5                  1035
#define IDC_EDIT_TEST6                  1036
#define IDC_EDIT_TEST7                  1037
#define IDC_EDIT_TEST8                  1038
#define IDC_EDIT_LOG                    1039
#define IDC_LIST_TESTS                  1040
#define IDC_LIST_LOG                    1040
#define IDC_EDIT_TEST10                 1040
#define IDC_EDIT_TEST99                 1040
#define IDC_EDIT_TEST11                 1041
#define IDC_EDIT_PASSWORD               1041
#define IDC_BUTTON_ADMIN1               1042
#define IDC_SPIN_COM_INTERFACE          1044
#define IDC_EDIT_COM_POWER_SUPPLY       1045
#define IDC_EDIT_COM_MULTIMETER         1046
#define IDC_EDIT_COM_INTERFACE          1047
#define IDC_SPIN_COM_MULTIMETER         1048
#define IDC_SPIN_COM_POWER_SUPPLY       1049
#define IDC_BUTTON_ADMIN2               1049
#define IDC_EDIT_MAX_FWHM_FILTER        1052
#define IDC_EDIT_PARTNUMBERS            1052
#define IDC_SPIN_MAX_CLOSED_FILTER_PEAK_AMPLITUDE 1053
#define IDC_EDIT_MAX_CLOSED_FILTER_PEAK_AMPLITUDE 1054
#define IDC_SPIN_MAX_IRRADIANCE_FILTER  1055
#define IDC_EDIT_MAX_WAVELENGTH_FILTER  1056
#define IDC_CHECK_SLC                   1056
#define IDC_SPIN_MAX_WAVELENGTH_FILTER  1057
#define IDC_EDIT1                       1057
#define IDC_EDIT_INT_TIME               1057
#define IDC_EDIT_MAX_IRRADIANCE_FILTER  1058
#define IDC_CHECK_LINEAR                1058
#define IDC_SPIN_MAX_FWHM_FILTER        1059
#define IDC_SPIN_INT_TIME               1059
#define IDC_EDIT_MIN_CLOSED_FILTER_PEAK_AMPLITUDE 1060
#define IDC_SPIN_NUM_AVERAGES           1060
#define IDC_EDIT_MIN_WAVELENGTH_FILTER  1061
#define IDC_SPIN_NUM_SCANS              1061
#define IDC_BUTTON1                     1061
#define IDC_BUTTON_RETRY                1061
#define IDC_EDIT_MIN_IRRADIANCE_FILTER  1062
#define IDC_EDIT_MIN_FWHM_FILTER        1063
#define IDC_SPIN_MIN_CLOSED_FILTER_PEAK_AMPLITUDE 1064
#define IDC_SPIN_MIN_WAVELENGTH_FILTER  1065
#define IDC_SPIN_MIN_IRRADIANCE_FILTER  1066
#define IDC_STATIC_PASSWORD             1066
#define IDC_SPIN_MIN_FWHM_FILTER        1067
#define IDC_BUTTON_PASSWORD             1067
#define IDC_SPIN_MAX_IRRADIANCE_OPEN    1068
#define IDC_STATIC_PASSWORD2            1068
#define IDC_EDIT_MAX_IRRADIANCE_OPEN    1069
#define IDC_EDIT_MIN_IRRADIANCE_OPEN    1070
#define IDC_SPIN_COM_INTERFACE12        1071
#define IDC_SPIN_MIN_IRRADIANCE_OPEN    1071
#define IDC_SPIN_MAX_COLOR_TEMP_OPEN    1072
#define IDC_EDIT_MAX_COLOR_TEMP_OPEN    1073
#define IDC_EDIT_MIN_COLOR_TEMP_OPEN    1074
#define IDC_SPIN_MIN_COLOR_TEMP_OPEN    1075
#define IDC_EDIT_LAMP_VOLTAGE           1076
#define IDC_EDIT_REF_VOLTAGE            1077
#define IDC_SPIN_LAMP_VOLTAGE           1078
#define IDC_SPIN_REF_VOLTAGE            1079
#define IDC_EDIT_INSTRUCT               1080
#define IDC_RADIO_PRIMARY               1080
#define IDC_RADIO_SECONDARY             1081
#define IDC_STATIC_SPREADSELECT         1082
#define ID_STATUSBAR                    1083
#define IDC_STATIC_FILENAME             1083
#define IDC_EDIT_MIN1                   1091
#define IDC_EDIT_MIN2                   1093
#define IDC_EDIT_MIN3                   1094
#define IDC_EDIT_MIN4                   1095
#define IDC_EDIT_MIN5                   1096
#define IDC_EDIT_MAX1                   1097
#define IDC_EDIT_MIN6                   1098
#define IDC_EDIT_MAX2                   1099
#define IDC_EDIT_MAX3                   1100
#define IDC_EDIT_MAX4                   1101
#define IDC_EDIT_MAX5                   1102
#define IDC_EDIT_MAX6                   1103
#define ID_FILE                         32771
#define ID_FILE_EXIT                    32772
#define ID_FILE_EXIT32773               32773
#define ID_ACTUATOR_OPEN                  32774
#define ID_ACTUATOR_CLOSED                 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
